language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: J9Ffz0cxq0LGZnlN5Om3F9orvUFybBbROenglIp98KXPMZD0rPTxY+kBBJhtD70L97xjCyY1+xm/izYunvRnG8WbN9PKJ4NQpoNiDEcW5tit1Ive1yVUFGSuihxKaLMoVEeA4xq9ddHyAQ+Xys130CKRKFo+GcQJbn/d3twI3kurNdUd2NCzT1tke0notd0rKWONHfAOyKoKJGirH1X1yHDEb0IcMyos16a9fTksUVwCCmq6G3DbQjzZkr6iasDpMxeMwLonEICP0c/impw7CIhiUJCRUxfxUwmKGN+S8Xq1kTKtc29heszJHzILtnMNEcISTT/xAeTPYNdqIeW+/m61sYNCrnE8Qi57bHa0gmtNwA/I7zZ10uTCn27ZsYiSDmKwQLHgvJi0uxnXGzeybAt9oMTO83qm3mhuEjskMWmPcWP8lu0yBg8jgCxnLLxLMX63rLqe+tYi9Gato6mU9gD+cZtMhb00BqgoC0+9ZO8q/UEblB09yW8SuB/r+Ga1qU5emDZvthqFxZ2dwWaR5ZeTmMh+1hmtBtnATWBhLMUHGMaPQ+6cLPn7ONJLgLA/ey2KAwXPJBX0VBbivKCtIcPkLgSk5WJjZHsUbPrHBtG8owDOCQ/IJpbFomBAKkSUZeWIfhDK/cbzh07MHpmt9VwUPz5OEJVje3MWY1WeEqI=
  - secure: agqPNcRbQ3OAWYZL03hht/NGYmtC4h2Ddz0iR8Htl/sBhkXDFpkNvBuUbRm4oHbnvmX2n8v8W7qo5U2mVOsYLu3GBVctrZltXW1pVtW84Qa0wuJbgPAwDdYtSLM/FaXce7TpdDC6YgoODPxbeybju6CVxJikwdpmzwAqzwFMroVuBntvnsFf0D/TnqhqfWBtxsYqNFkmWQUsq04Sn1PXgL2vq0sWZmFAvn26RFuVjL6uIW4DTjLNpKnojfJ5Xe79RoYggnxBq2CXNNtOPzdyXsFGL9rZZOdftbAPYOe2zGM8ERs0oUxeDHzt6vhkVakKG51qIVGqq82EHY0LenCUFN78Z+HSZPgLWKywi5VHKu42ZNgtm0ECoweU+zxR2gd2+WRCVgrY/D/gjxmxSHV0kEQCYtrEuP9L8Wp2OSaJmDhSJA6BbEIjMy68x4eYWGf+h5Wib3zLnmWtbuViWGAefZhJvAj1+Soy/q5/8IV3bYbwCE94OihK7xOd+dLzMB9dO4D9n44aUOZMIGP2zp83mH61w4VhcCuUDzB76FkBoJPTgR4ZdJwhq7zZep3yZm5qQKYdS3hzoIQymOopMGuW2lp/bOKSdZeR8nZZ3+VukSXTMq+9RG33yEAieymR2n5EjotKn9zQpcySqpLBFDF9IrJoJSbJp8JYdjEwY9hsqNg=
