baseURL = "https://www.yapper.io/"
languageCode = "en-us"
title = "theYapper"
author = "theYapper"
copyright = "Copyright (c) 2008 - 2017, theYapper; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-theme-minos"

[[menu.main]]
    name = "TAGS"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

#[[menu.main]]
#    name = "CATEGORIES"
#   pre = "<i class='fa fa-folder-open'></i>"
#   weight = -100
#   identifier = "categories"
#   url = "/categories/"


[[menu.main]]
    name = "ABOUT ME"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "about-me"
    url = "/page/about"

[[menu.footer]]
    name = "DISCLAIMER"
    weight = -110
    identifier = "disclaimer"
    url = "/page/disclaimer/"

[[menu.footer]]
    name = "LICENSE"
    weight = -120
    identifier = "license"
    url = "/page/license/"

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = true
